### ISSUE TITLE
document the default representation for schema Union types

### ISSUE THREAD

**Issue by mvdan** [ipld/ipld#129]
From @warpfork:

> at type level, unions should act like keyed, and use the type name

We should clarify this in the docs in https://ipld.io/docs/schemas/features/representation-strategies/.

**Comment by rvagg** [comment]
Oh, well that's not really the default representation, more like the default behaviour. Do we have anything else similar in the schemas at the moment? And, how much of this is a user concern, does it impact API or just internal strategies?

**Comment by warpfork** [comment]
Yeah, default "representation" isn't quite how I'd describe this.  I'd put it as:

- At the type level, a value of union typekind always acts like a data model map kind.
  - This map always has exactly one key, which is the inhabitant's type name.
    - (This is very similar to what a keyed Union's representation behavior is, too -- except because this is a _type_ behavior, it is _not customizable_.)
    - (E.g., normally, you'll see a string with TitleCase here, assuming your type names are using TitleCase, as is convention.)
- A union type has no default representation.  You must always specify a representation strategy when defining a union type.

As to how similar this is to other things: quite a bit.  I think if we did a fresh pass on the schema chapters of the docs and specs at this point, we'd probably make a point of consistently having a "typekind behavior" h4 section for each typekind, and a "representation strategies" h4 following it.  And all of the "typekind behavior" sections would repeat the statement about "because this is a type behavior, it is not customizable".

**Comment by BigLep** [comment]
Closing out as not high enough priority to act on.
