### ISSUE TITLE
How does implicit modifier on structs work ?

### ISSUE THREAD

**Issue by Gozala** [ipld/ipld#268]
I'm keep finding that my intuition about `implicit` modifier is not supported by the schema toolchain & existing documentation is not really clear about it either specifically I would expect following to be valid schema syntax

```ipldsch
type Task struct {
  with    string
  do      string
  input   {String: any} (implicit {})

  nnc     string (implicit "")
  prf      [&UCAN] (implicit [])
}
```

Yet all my implicit declarations seem invalid, following seems ok though

```ipldsch
type Task struct {
  with    string
  do      string
  input   {String: any} (implicit "{}")

  nnc     string (implicit "''")
  prf      [&UCAN] (implicit "[]")
}
```

Yet I have no idea if later defines what I intended in former, that is:

1. `input` is implicitly an empty map.
2. `nnc` is implicitly an empty string.
3. `prf` is implicitly an empty array.

I'm almost certain `nnc` is not going to be implicitly an empty string, yet I have no idea what would be a valid syntax for it or whether one even exists

**Comment by rvagg** [comment]
Current tooling only supports implicits for scalar values. There's not much point in doing anything but this. Your implicit map and list are unnecessary because if it's not `optional` or `nullable` then it's going to be an empty list or map anyway; just leave it off those places. https://github.com/ipld/ipld/blob/85148147ef73cd1ef9d6bf0c0934006e40e4bd80/specs/schemas/schema-schema.ipldsch#L646

There's pretty basic support in JS for implicits, it'll codegen you a default that's just what you provide it and assume it was a scalar without checking. It should check, in fact the toolchain should complain somewhere about trying to set them on lists or maps.

In your case, none of these implicits should be required. `input` should come back as an empty map where not defined, `nnc` should be an empty string, `prf` should be an empty list; take off the implicits and that _should_ be the meaning. Where that's not holding true then we have bugs that ought to get fixed!

```ipldsch
type Task struct {
  with    String
  do      String
  input   {String:any}
  nnc     String
  prf      [&UCAN]
}
```

This might be a good test case to add and assert that we actually get an empty map, empty list and empty string and not `null` values. Part of the hassle here is that in JS these things will be nullable by default, so we have to set them. The nice part of doing this in Go with bindnode is that you have to match a pointer field to a nullable/optional and where you don't, you get the language default zero values for them.

**Comment by Gozala** [comment]
> then it's going to be an empty list or map anyway; just leave it off those places.

Would empty map and list be omitted from serialized representation as well or am I expected to manually set those ?

> There's pretty basic support in JS for implicits, it'll codegen you a default that's just what you provide it and assume it was a scalar without checking. It should check, in fact the toolchain should complain somewhere about trying to set them on lists or maps.

👍

Thanks for the explanation

**Comment by rvagg** [comment]
> Would empty map and list be omitted from serialized representation as well

they _should_ be set to empty map/list if they're not optional or nullable - anything that's not optional or nullable should have a zero value and map and list zero values should be empty

I'm going to have to go back and consider all these non-scalar cases in js-ipld-schema cause I'm sure it's being very javascripty about it which isn't right

**Comment by rvagg** [comment]
I think I'll move this to https://github.com/ipld/js-ipld-schema/issues/83 and consider this question closed for now, perhaps I'll find some surprising edges I'm not considering when implementing this
